services:
  # Database PostgreSQL untuk penyimpanan permanen transaksi
  db:
    image: postgres:15-alpine
    container_name: qris_postgres_legacy
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: qrislegacy
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: