apiVersion: 1

datasources:
  - name: QRIS K6 InfluxDB
    uid: qris-k6-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: false
    jsonData:
      httpMode: GET
